/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestIndexRouteImport } from './routes/test.index'
import { Route as PrijavaIndexRouteImport } from './routes/prijava.index'
import { Route as NovicaIndexRouteImport } from './routes/novica/index'
import { Route as ConverterIndexRouteImport } from './routes/converter/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ApiConverterRouteImport } from './routes/api/converter'
import { Route as NovicaArticle_slugIndexRouteImport } from './routes/novica/$article_slug.index'
import { Route as AdminStatusIndexRouteImport } from './routes/admin/$status/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminStatusArticle_slugIndexRouteImport } from './routes/admin/$status/$article_slug.index'
import { Route as AdminStatusArticle_slugUrediIndexRouteImport } from './routes/admin/$status/$article_slug.uredi.index'

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestIndexRoute = TestIndexRouteImport.update({
  id: '/test/',
  path: '/test/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrijavaIndexRoute = PrijavaIndexRouteImport.update({
  id: '/prijava/',
  path: '/prijava/',
  getParentRoute: () => rootRouteImport,
} as any)
const NovicaIndexRoute = NovicaIndexRouteImport.update({
  id: '/novica/',
  path: '/novica/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConverterIndexRoute = ConverterIndexRouteImport.update({
  id: '/converter/',
  path: '/converter/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiConverterRoute = ApiConverterRouteImport.update({
  id: '/api/converter',
  path: '/api/converter',
  getParentRoute: () => rootRouteImport,
} as any)
const NovicaArticle_slugIndexRoute = NovicaArticle_slugIndexRouteImport.update({
  id: '/novica/$article_slug/',
  path: '/novica/$article_slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStatusIndexRoute = AdminStatusIndexRouteImport.update({
  id: '/$status/',
  path: '/$status/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStatusArticle_slugIndexRoute =
  AdminStatusArticle_slugIndexRouteImport.update({
    id: '/$status/$article_slug/',
    path: '/$status/$article_slug/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminStatusArticle_slugUrediIndexRoute =
  AdminStatusArticle_slugUrediIndexRouteImport.update({
    id: '/$status/$article_slug/uredi/',
    path: '/$status/$article_slug/uredi/',
    getParentRoute: () => AdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/api/converter': typeof ApiConverterRoute
  '/admin/': typeof AdminIndexRoute
  '/converter': typeof ConverterIndexRoute
  '/novica': typeof NovicaIndexRoute
  '/prijava': typeof PrijavaIndexRoute
  '/test': typeof TestIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/$status': typeof AdminStatusIndexRoute
  '/novica/$article_slug': typeof NovicaArticle_slugIndexRoute
  '/admin/$status/$article_slug': typeof AdminStatusArticle_slugIndexRoute
  '/admin/$status/$article_slug/uredi': typeof AdminStatusArticle_slugUrediIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/converter': typeof ApiConverterRoute
  '/admin': typeof AdminIndexRoute
  '/converter': typeof ConverterIndexRoute
  '/novica': typeof NovicaIndexRoute
  '/prijava': typeof PrijavaIndexRoute
  '/test': typeof TestIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/$status': typeof AdminStatusIndexRoute
  '/novica/$article_slug': typeof NovicaArticle_slugIndexRoute
  '/admin/$status/$article_slug': typeof AdminStatusArticle_slugIndexRoute
  '/admin/$status/$article_slug/uredi': typeof AdminStatusArticle_slugUrediIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/api/converter': typeof ApiConverterRoute
  '/admin/': typeof AdminIndexRoute
  '/converter/': typeof ConverterIndexRoute
  '/novica/': typeof NovicaIndexRoute
  '/prijava/': typeof PrijavaIndexRoute
  '/test/': typeof TestIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/$status/': typeof AdminStatusIndexRoute
  '/novica/$article_slug/': typeof NovicaArticle_slugIndexRoute
  '/admin/$status/$article_slug/': typeof AdminStatusArticle_slugIndexRoute
  '/admin/$status/$article_slug/uredi/': typeof AdminStatusArticle_slugUrediIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/api/converter'
    | '/admin/'
    | '/converter'
    | '/novica'
    | '/prijava'
    | '/test'
    | '/api/auth/$'
    | '/admin/$status'
    | '/novica/$article_slug'
    | '/admin/$status/$article_slug'
    | '/admin/$status/$article_slug/uredi'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/converter'
    | '/admin'
    | '/converter'
    | '/novica'
    | '/prijava'
    | '/test'
    | '/api/auth/$'
    | '/admin/$status'
    | '/novica/$article_slug'
    | '/admin/$status/$article_slug'
    | '/admin/$status/$article_slug/uredi'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/api/converter'
    | '/admin/'
    | '/converter/'
    | '/novica/'
    | '/prijava/'
    | '/test/'
    | '/api/auth/$'
    | '/admin/$status/'
    | '/novica/$article_slug/'
    | '/admin/$status/$article_slug/'
    | '/admin/$status/$article_slug/uredi/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ApiConverterRoute: typeof ApiConverterRoute
  ConverterIndexRoute: typeof ConverterIndexRoute
  NovicaIndexRoute: typeof NovicaIndexRoute
  PrijavaIndexRoute: typeof PrijavaIndexRoute
  TestIndexRoute: typeof TestIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  NovicaArticle_slugIndexRoute: typeof NovicaArticle_slugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/': {
      id: '/test/'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prijava/': {
      id: '/prijava/'
      path: '/prijava'
      fullPath: '/prijava'
      preLoaderRoute: typeof PrijavaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novica/': {
      id: '/novica/'
      path: '/novica'
      fullPath: '/novica'
      preLoaderRoute: typeof NovicaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/converter/': {
      id: '/converter/'
      path: '/converter'
      fullPath: '/converter'
      preLoaderRoute: typeof ConverterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/converter': {
      id: '/api/converter'
      path: '/api/converter'
      fullPath: '/api/converter'
      preLoaderRoute: typeof ApiConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novica/$article_slug/': {
      id: '/novica/$article_slug/'
      path: '/novica/$article_slug'
      fullPath: '/novica/$article_slug'
      preLoaderRoute: typeof NovicaArticle_slugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$status/': {
      id: '/admin/$status/'
      path: '/$status'
      fullPath: '/admin/$status'
      preLoaderRoute: typeof AdminStatusIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$status/$article_slug/': {
      id: '/admin/$status/$article_slug/'
      path: '/$status/$article_slug'
      fullPath: '/admin/$status/$article_slug'
      preLoaderRoute: typeof AdminStatusArticle_slugIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/$status/$article_slug/uredi/': {
      id: '/admin/$status/$article_slug/uredi/'
      path: '/$status/$article_slug/uredi'
      fullPath: '/admin/$status/$article_slug/uredi'
      preLoaderRoute: typeof AdminStatusArticle_slugUrediIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminStatusIndexRoute: typeof AdminStatusIndexRoute
  AdminStatusArticle_slugIndexRoute: typeof AdminStatusArticle_slugIndexRoute
  AdminStatusArticle_slugUrediIndexRoute: typeof AdminStatusArticle_slugUrediIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminStatusIndexRoute: AdminStatusIndexRoute,
  AdminStatusArticle_slugIndexRoute: AdminStatusArticle_slugIndexRoute,
  AdminStatusArticle_slugUrediIndexRoute:
    AdminStatusArticle_slugUrediIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ApiConverterRoute: ApiConverterRoute,
  ConverterIndexRoute: ConverterIndexRoute,
  NovicaIndexRoute: NovicaIndexRoute,
  PrijavaIndexRoute: PrijavaIndexRoute,
  TestIndexRoute: TestIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  NovicaArticle_slugIndexRoute: NovicaArticle_slugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
